name: CI Test

on:
  push:
    branches:
      - test
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install poetry
        poetry install --no-root

    - name: Lint with ruff
      run: |
            poetry run ruff . --fix

    - name: Run pytest
      id: pytest
      run: |
        pytest 